let a:string="Introduction";
let b:string=" to TypeScript";
let c:string=",";
var z=a.charAt(4);
console.log("charAt : "+z);
console.log("---------------------------------------");
var y=a.concat(b);
console.log("concat : "+y);
console.log("---------------------------------------");
var x=b.indexOf("S");
console.log("indexOf : "+x);
console.log("---------------------------------------");
var w=b.replace("T","t");
console.log("replace : "+w);
console.log("---------------------------------------");
var v=b.split(c);
console.log("split : "+v);
console.log("---------------------------------------");
var u=a.toUpperCase();
console.log("toUpperCase : "+u);
console.log("---------------------------------------");
var t=b.toLowerCase();
console.log("toLowerCase : "+t);
console.log("---------------------------------------");